import type { Metadata } from "next";
import { Geist, Geist_Mono, Playfair_Display } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { JobProvider } from "./context/JobContext";
import { ToastProvider } from "./context/ToastContext";
import ToastContainer from "./components/Toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const playfair = Playfair_Display({
  variable: "--font-display",
  subsets: ["latin"],
  weight: ["500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${playfair.variable} antialiased`}
      >
        <div className="flex min-h-screen flex-col text-slate-100">
          <Navbar />
          <main className="flex-1">
              <ToastProvider>
                <JobProvider>{children}</JobProvider>
                <ToastContainer />
              </ToastProvider>
            </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
